version: '3'
services:
  redis:
    image: redis

  rq-worker:
    restart: always
    build: ..
    depends_on: 
      - redis

    command: rqworker --with-scheduler --url redis://redis:6379
  
  postgres:
    image: postgres:alpine
    volumes:
      - /lib/postgres/postgres-data:/var/lib/postgresql/data
      - ../db:/docker-entrypoint-initdb.d/
    env_file: 
      - ../.env
    ports:
      - "5432:5432"
    
  fiano_monitoring:
    restart: always
    depends_on:
      - postgres
      - redis
    build: ..
    ports: 
      - "8000:8000"
      - "5000:5000"
    command: python -m flask run -h 0.0.0.0
    volumes: 
      - ..:/src
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fiano_monitoring.rule=Host(`fiano-monitoring.adylanrff.com`)"
      - "traefik.http.routers.fiano_monitoring.entrypoints=websecure"
      - "traefik.http.routers.fiano_monitoring.tls.certresolver=myresolver"
      - "traefik.http.routers.fiano_monitoring.tls=true"
    env_file: 
      - ../.env
  
  grafana:
    restart: always
    image: grafana/grafana
    depends_on:
      - postgres
    ports: 
      - "3000:3000"
    volumes: 
      - grafana-storage:/var/lib/grafana
      - ../grafana/grafana.ini:/etc/grafana/grafana.ini
    env_file: 
      - ../.env
volumes:
  grafana-storage:
    external: true
