version: '3'
services:
  redis:
    image: redis
    ports: 
      - "6379:6379"

  rq-worker:
    restart: always
    build: ..
    depends_on: 
      - redis

    command: rqworker --with-scheduler --url redis://redis:6379
  
  postgres:
    image: postgres:alpine
    volumes:
      - /lib/postgres/postgres-data:/var/lib/postgresql/data
      - ../db:/docker-entrypoint-initdb.d/  
    env_file: 
      - ../.env
    ports:
      - "5432:5432"
